# Array
- Vector: A vector is an array with a single dimension
- Matrix: A matrix refers to an array with two dimensions
- Tensor: For 3D or higher dimensional arrays, the term TENSOR is also commonly used
#### TensorFlow is a free and open-source software library for ML and AI

### 1D Array (Vector)

In [1]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
len(a)

3

In [4]:
a[0]

5

In [5]:
a[0:]

array([5, 5, 5])

### Some other types of 1-D array

In [6]:
# 1- zeros
b = np.zeros(2)
b

array([0., 0.])

In [7]:
# 2- ones
c = np.ones(2)
c

array([1., 1.])

In [8]:
# 3- empty
d = np.empty(3)
d

array([1.89144010e-307, 3.33772113e-307, 1.89146896e-307])

In [9]:
# 4- range
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [10]:
# 5- Specific range
f = np.arange(2, 20) #last digit is exclusive (here 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [11]:
# 6- linear spaced array
f = np.linspace(0,10,num=5) #give us 5 numbers
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 2D Array (Matrix)

In [12]:
# list 0f lists

g = np.array([[5,5,5],[5,5,5],[5,5,5]])
g

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
type(g)

numpy.ndarray

In [14]:
len(g)

3

In [15]:
g[0]

array([5, 5, 5])

In [16]:
g[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Some other types of 2-D array

In [17]:
# 1- zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# 2- ones
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
# 3- empty
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###  Array Attributes

In [20]:
# example of 2-axis array (Example:1)
# First axis (coloumn) has length = 2
# Second axis (row) has length = 3

h = np.array([[5,5,5],[5,5,5]])
h

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [22]:
# specific data types in array (Example:2)
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

# 3-D Array

In [23]:
# Making and Reshaping a 3D array
k = np.arange(36).reshape(3,3,4)
k

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])