# Functions

### 1D Array

In [1]:
import numpy as np

food = np.array(["Pakora","Samosa","Chatni"])
price = np.array([5,5,5])

In [2]:
# f1 (mean)
price.mean()

5.0

In [3]:
# f2 (zeros)
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
# f3 (ones)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# f4 (empty)
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
# f6 (range)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# f7 (specific range)
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
# f8 (specific range with intterval)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# f9 (table of 5)
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
# f10 (specific linespace)
np.linspace(1,100,num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [22]:
# f11 (specify your data type)
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [28]:
# f12 (sort)
a = np.array([10,6,8,32,14,19,2,8,13,17,1,34])
a.sort()
a

array([ 1,  2,  6,  8,  8, 10, 13, 14, 17, 19, 32, 34])

In [30]:
# f13 (concatenate)
b = np.array ([10.2, 2.4, 91.6, 45.5, 7.8])

c=np.concatenate((a,b))
c

array([ 1. ,  2. ,  6. ,  8. ,  8. , 10. , 13. , 14. , 17. , 19. , 32. ,
       34. , 10.2,  2.4, 91.6, 45.5,  7.8])

---

### 2D Array

In [31]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [37]:
b = np.array([[6,7,8,9,10],[10,9,8,7,6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [39]:
# f1 (concatenae)
c = np.concatenate((a,b))
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [41]:
# axis=1
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [47]:
# Creating 3D usiing 2D array

a=np.array([[[0,1,2,3],
             [4,5,6,7]],     #first dimension
            
            [[0,1,2,3],
            [4,5,6,7]],      #second dimension
           
           [[0,1,2,3],
            [4,5,6,7]]])     #third dimension
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [46]:
# to find the no of dimension
a.ndim

3

In [48]:
# size of array (no of elements)
a.size

24

In [50]:
# shape of array (dimensions, coloumns, rows)
a.shape         

(3, 2, 4)

In [68]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [66]:
# Reshape
a = a.reshape(9,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [70]:
# convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a.shape

(9,)

In [71]:
# row-wise 2D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
b.shape

(1, 9)

In [74]:
# coloumn-wise 2D coversion
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [78]:
# So
a,b,c

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))